export default Globals = {
    BASE_URL: 'http://localhost:3000/',
    COLOR: {
        MAINCOLOR: '#fc4a1a',
        MAINCOLOR2:'#F3F4F6',
    },
    GRADIENT_COLOR: ['#43C6AC', '#000046'],
    GRADIENT_OPACITY: 0.7,
    ICONSIZE: 30,
    TITLESIZE_BIG: 40,
    TITLESIZE_MEDIUM: 35,
    APPNAME: 'BookStore'
};

export const FETCHING_BOOK_PROMOTION = "FETCHING_BOOK_PROMOTION";
export const FETCHING_BOOK_PROMOTION_SUCCESS = "FETCHING_BOOK_PROMOTION_SUCCESS";
export const FETCHING_BOOK_PROMOTION_FAIL = "FETCHING_BOOK_PROMOTION_FAIL";