export default Globals = {
    BASE_URL: 'http://localhost:3000/',
    COLOR: {
        MAINCOLOR: '#fc4a1a',
        MAINCOLOR2:'#F3F4F6',
    },
};

export const FETCHING_BOOK_PROMOTION = "FETCHING_BOOK_PROMOTION";
export const FETCHING_BOOK_PROMOTION_SUCCESS = "FETCHING_BOOK_PROMOTION_SUCCESS";
export const FETCHING_BOOK_PROMOTION_FAIL = "FETCHING_BOOK_PROMOTION_FAIL";