export default Globals = {
    BASE_URL: 'https://tohiti-bookstore-backend.herokuapp.com/',
    COLOR: {
        MAINCOLOR: '#fc4a1a',
        MAINCOLOR2:'#F3F4F6',
    },
    GRADIENT_COLOR: ['#43C6AC', '#000046'],
    GRADIENT_OPACITY: 0.7,
    ICONSIZE: 30,
    TITLESIZE_BIG: 40,
    TITLESIZE_MEDIUM: 35,
    APPNAME: 'BookStore',
    FONT:{fontFamily: 'OpenSans-Regular',}
};

export const FETCHING_PROMOTION_BOOKS = "FETCHING_PROMOTION_BOOKS";
export const FETCHING_PROMOTION_BOOKS_SUCCESS = "FETCHING_PROMOTION_BOOKS_SUCCESS";
export const FETCHING_PROMOTION_BOOKS_FAIL = "FETCHING_PROMOTION_BOOKS_FAIL";


export const FETCHING_NEW_BOOKS = "FETCHING_NEW_BOOKS";
export const FETCHING_NEW_BOOKS_SUCCESS = "FETCHING_NEW_BOOKS_SUCCESS";
export const FETCHING_NEW_BOOKS_FAIL = "FETCHING_NEW_BOOKS_FAIL";


export const FETCHING_ACCESS_TOKEN = 'FETCHING_ACCESS_TOKEN';
export const FETCHING_ACCESS_TOKEN_SUCCESS = 'FETCHING_ACCESS_TOKEN_SUCCESS';
export const FETCHING_ACCESS_TOKEN_FAIL = 'FETCHING_ACCESS_TOKEN_FAIL';